language: rust

rust:
  nightly

install:
  - cargo install --git https://github.com/alexcrichton/wasm-gc

script:
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - make
  - mkdir out
  - cp index.html out
  - cp rust.wasm out

deploy:
  local-dir: out
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
